POST http://localhost:4000/login
Content-Type: application/json

{
  "email": "lulamonroe@uni.com",
  "password": "Pass@1234"
}
###
GET http://localhost:4000/feed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTg0ZWJhZmJhOTIzMzQyOWFlYzkwMyIsInBpY3R1cmUiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi80OCIsIm5hbWUiOiJMdWxhIE1vbnJvZSIsImdlbmRlciI6ImZlbWFsZSIsImVtYWlsIjoibHVsYW1vbnJvZUB1bmkuY29tIiwicmVnaXN0ZXJlZCI6IjIwMTYtMDMtMjZUMDQ6MzY6NDggLTA2Oi00NSIsImlhdCI6MTY0MjYxNjEwNn0.39TzExmiNwYRwhw0DbuvsAFxTHoSrHxTM3KEXGcPaoQ
###
GET http://localhost:4000/friends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTg0ZWJhZmJhOTIzMzQyOWFlYzkwMyIsInBpY3R1cmUiOiJodHRwczovL3JhbmRvbXVzZXIubWUvYXBpL3BvcnRyYWl0cy93b21lbi80OCIsIm5hbWUiOiJMdWxhIE1vbnJvZSIsImdlbmRlciI6ImZlbWFsZSIsImVtYWlsIjoibHVsYW1vbnJvZUB1bmkuY29tIiwicmVnaXN0ZXJlZCI6IjIwMTYtMDMtMjZUMDQ6MzY6NDggLTA2Oi00NSIsImlhdCI6MTY0MjYxNjEwNn0.39TzExmiNwYRwhw0DbuvsAFxTHoSrHxTM3KEXGcPaoQ